version: '3'

name: 'zenmirai-nestjs-lib-storage-infrastructure'

services:
  app:
    container_name: zenmirai-nestjs-lib-storage-app
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    command: "/bin/sh -c 'bun i && bun start:dev'"
    ports:
      - '4000:4000'
    volumes:
      - .:/app
