export enum Direction {
  DOMESTIC_TRANSFER = 'DOMESTIC_TRANSFER',
  DOMESTIC_SPECIAL_TRANSFER = 'DOMESTIC_SPECIAL_TRANSFER',
  FOREIGN_INBOUND_SPECIAL_TRANSFER = 'FOREIGN_INBOUND_SPECIAL_TRANSFER',
}