export const FLIP_DECORATOR_PREFIX = 'FLIP_LIB';

export const FLIP_CONFIG_OPTION_TOKEN = `${FLIP_DECORATOR_PREFIX}CONFIG`;
export const FLIP_CONFIG_SERVICE_TOKEN = `${FLIP_DECORATOR_PREFIX}SERVICE`;
